name: camera_ros build

on: [push, pull_request]

jobs:
  build:
    name: camera_ros (${{ matrix.distribution }})
    runs-on: ubuntu-22.04

    # Test on the latest LTS and current version ('rolling'),
    # but only require to pass on LTS distributions.
    strategy:
      matrix:
        distribution: ["humble", "rolling"]
    continue-on-error: ${{ matrix.distribution == 'rolling' }}

    steps:
      - name: install colcon-meson
        run: |
          pip install colcon-meson

      - name: fetch source
        uses: actions/checkout@v2

      - name: install ROS2 ${{ matrix.distribution }}
        uses: ros-tooling/setup-ros@v0.3

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: camera_ros
          target-ros2-distro: ${{ matrix.distribution }}
          vcs-repo-file-url: .github/repo.yaml
          colcon-defaults: |
            {
              "build": {
                "mixin": ["asan-gcc"]
              },
              "names": {
                "libcamera": {
                  "meson-args": ["--auto-features=disabled", "-Dtest=false", "-Dipas=[]"]
                }
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/3e627e0fa30db85aea05a50e2c61a9832664d236/index.yaml
