name: camera_ros build

on: [push, pull_request]

jobs:
  build:
    name: camera_ros (${{ matrix.distribution }})
    runs-on: ubuntu-latest
    # Test on the latest LTS and current version ('rolling'),
    # but only require to pass on LTS distributions.
    strategy:
      matrix:
        distribution: ["foxy", "rolling"]
    continue-on-error: ${{ matrix.distribution == 'rolling' }}

    steps:
      - name: install libcamera
        run: |
          sudo apt install python3-pip ninja-build python3-yaml python3-ply python3-jinja2 libgnutls28-dev
          sudo pip3 install meson
          git clone -n https://git.libcamera.org/libcamera/libcamera.git
          cd libcamera
          git checkout --detach 5c85e7024027c90b1b054782e510691b8b9c7419
          meson build --buildtype release -Dcam=disabled -Ddocumentation=disabled -Dgstreamer=disabled -Dipas="" -Dlc-compliance=disabled -Dpipelines=simple -Dqcam=disabled -Dtest=false -Dtracing=disabled -Dv4l2=false
          meson compile -C build
          sudo meson install -C build

      - name: install ROS2 ${{ matrix.distribution }}
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: ${{ matrix.distribution }}

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: camera_ros
          target-ros2-distro: ${{ matrix.distribution }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["asan-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/3e627e0fa30db85aea05a50e2c61a9832664d236/index.yaml
